SELECT TOP (10) [productcategory]
      ,[productsubcategory]
      ,[product]
      ,[saleterritory]
      ,[Country]
      ,[City]
      ,[Sate]
      ,[Customer]
      ,[Employee]
      ,[OrderCount]
      ,[OrderDate]
      ,[StandardCost]
      ,[UnitPrice]
      ,[UnitPriceDiscount]
      ,[Discount]
      ,[ListPrice]
      ,[SaleswithStandard]
      ,[NetSales]
      ,[OrderQuantity]
      ,[Sales]
  FROM [master].[dbo].[AdvWorksData]